### ISSUE TITLE
Typo in `benchmark.ml` ?

### ISSUE THREAD

**Issue by lyrm** [dinosaure/bechamel#11]
Hi, 
Should the value used as the maximum number of times the benchmarked function is run actually be `!run` instead of `!idx` ? 
[Link here](https://github.com/dinosaure/bechamel/blob/f1b3db0115af3854422697134a1555e3c07a19f5/lib/benchmark.ml#L67)
Copy of the line :
````ocaml
 while (not (exceeded_allowed_time cfg.quota init_time)) && !idx < cfg.run do
````

**Comment by dinosaure** [comment]
Yes, you are right, I will propose a fix.
