### ISSUE TITLE
Using bechamel-perf requires running the benchmark with root privilege

### ISSUE THREAD

**Issue by OlivierNicole** [dinosaure/bechamel#31]
On my system, unless using `sudo` the `perf_event_open` syscall fails with “Permission denied”. [A quick search](https://stackoverflow.com/questions/66146189/permission-denied-on-perf-event-open-is-there-another-way-than-to-use-sudo-or-c) suggests this might be due to the `exclude_kernel = 0` and `exclude_hv = 0` attributes in the C stub.

**Comment by dinosaure** [comment]
We should probably update the documentation and explain the environment for using some of the features offered by `perf' indeed.

**Comment by dinosaure** [comment]
Fixed by #39 which explains required privileges when we use `Bechamel_perf`.
